Customs = {}

Customs.VehicleModels = {
	[GetHashKey("yFiat595ssB")] = {
		["name"] = "",
		["brand"] = "Sidney Mobile",
		["model"] = "yFiat595ssB",
		["price"] = 0,
		["category"] = "coupes",
		["hash"] = GetHashKey("yFiat595ssB"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 40000,
		["trunkslots"] = 40,
		["shop"] = "nfs",
	},
	[GetHashKey("raptor2017")] = {
		["name"] = "RAPTOR",
		["brand"] = "Ford Raptor 2017",
		["model"] = "raptor2017",
		["price"] = 567000,
		["category"] = "4x4",
		["hash"] = GetHashKey("raptor2017"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/9/9c/Penetrator-GTAO-front.png",
		["trunkspace"] = 100000,
		["trunkslots"] = 10,
		["shop"] = "pdm",
	},
	[GetHashKey("c7")] = {
		["name"] = "Chevrolet",
		["brand"] = "Corvette C7 Stingray",
		["model"] = "c7",
		["price"] = 340000,
		["category"] = "coupes",
		["hash"] = GetHashKey("c7"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 40000,
		["trunkslots"] = 40,
		["shop"] = "custom",
	},
	[GetHashKey("m3e46")] = {
		["name"] = "M3 E46",
		["brand"] = "BMW",
		["model"] = "m3e46",
		["price"] = 240000,
		["category"] = "coupes",
		["hash"] = GetHashKey("m3e46"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 50000,
		["trunkslots"] = 50,
		["shop"] = "custom",
	},
	[GetHashKey("750iL")] = {
		["name"] = "750iL",
		["brand"] = "BMW",
		["model"] = "750iL",
		["price"] = 150000,
		["category"] = "coupes",
		["hash"] = GetHashKey("750iL"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 50000,
		["trunkslots"] = 50,
		["shop"] = "custom",
	},
	[GetHashKey("mgt")] = {
		["name"] = "Ford",
		["brand"] = "Mustang GT",
		["model"] = "mgt",
		["price"] = 210000,
		["category"] = "coupes",
		["hash"] = GetHashKey("mgt"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 60000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},
	[GetHashKey("na1")] = {
		["name"] = "Honda",
		["brand"] = "NSX",
		["model"] = "na1",
		["price"] = 175000,
		["category"] = "coupes",
		["hash"] = GetHashKey("na1"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 40000,
		["trunkslots"] = 40,
		["shop"] = "custom",
	},
	[GetHashKey("rmodgt63")] = {
		["name"] = "GT63 S Coupe",
		["brand"] = "Mercedes",
		["model"] = "rmodgt63",
		["price"] = 410000,
		["category"] = "coupes",
		["hash"] = GetHashKey("rmodgt63"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 60000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},	
	[GetHashKey("g65amg")] = {
		["name"] = "G65 AMG",
		["brand"] = "Mercedes",
		["model"] = "g65amg",
		["price"] = 375000,
		["category"] = "coupes",
		["hash"] = GetHashKey("g65amg"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 150000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},
	[GetHashKey("s600w220")] = {
		["name"] = "S600",
		["brand"] = "Mercedes",
		["model"] = "s600w220",
		["price"] = 175000,
		["category"] = "coupes",
		["hash"] = GetHashKey("s600w220"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 100000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},
	[GetHashKey("skyline")] = {
		["name"] = "Nissan",
		["brand"] = "Skyline R34",
		["model"] = "skyline",
		["price"] = 230000,
		["category"] = "coupes",
		["hash"] = GetHashKey("skyline"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 50000,
		["trunkslots"] = 50,
		["shop"] = "custom",
	},
	[GetHashKey("tampa3")] = {
		["name"] = "G",
		["brand"] = "Tampa Drifting",
		["model"] = "tampa3",
		["price"] = 340000,
		["category"] = "coupes",
		["hash"] = GetHashKey("tampa3"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 60000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},
	[GetHashKey("yosemite6str")] = {
		["name"] = "G",
		["brand"] = "Yosemite 6STR",
		["model"] = "yosemite6str",
		["price"] = 340000,
		["category"] = "coupes",
		["hash"] = GetHashKey("yosemite6str"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 60000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},		
	[GetHashKey("r35")] = {
		["name"] = "GTR R35",
		["brand"] = "Nissan",
		["model"] = "r35",
		["price"] = 340000,
		["category"] = "coupes",
		["hash"] = GetHashKey("r35"),
		["image"] = "https://vignette.wikia.nocookie.net/gtawiki/images/0/07/FaggioMod-GTAO-front.png",
		["trunkspace"] = 60000,
		["trunkslots"] = 60,
		["shop"] = "custom",
	},

}
